## Gaussian Naive Bayes

In [3]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

import pandas as pd

iris = pd.read_csv('iris_2D_3C.csv')

# Seperating the data into dependent and independent variables
X_train = iris.iloc[:, :-1].values
y_train = iris.iloc[:, -1].values

In [4]:
X_train

array([[4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [6.4, 3.2],
       [6.9, 3.1],
       [5.5, 2.3],
       [6.5, 2.8],
       [5.7, 2.8],
       [6.3, 3.3],
       [5.6, 2.2],
       [5.1, 1.5],
       [5.6, 1.4],
       [5.9, 2.1],
       [5.3, 1.8],
       [5.7, 1.9]])

In [14]:
X_train[:,1]

array([3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3])

In [5]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int64)

In [8]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

classifier = GaussianNB()
clf = classifier.fit(X_train, y_train)

In [13]:
# predict
x_test = np.array([[5.2, 2.4]])
clf.predict_proba(x_test)

array([[0.0418694 , 0.19180669, 0.76632391]])

In [14]:
clf.class_prior_

array([0.33333333, 0.33333333, 0.33333333])

In [15]:
clf.var_

array([[0.07888889, 0.09555556],
       [0.22805556, 0.11138889],
       [0.06888889, 0.08472222]])

In [16]:
clf.theta_

array([[4.86666667, 3.36666667],
       [6.21666667, 2.91666667],
       [5.53333333, 1.81666667]])

## Compute manually

In [18]:
import math

def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var)) * np.exp(-(data-mean)**2 / (2*var))

In [22]:
means = np.array([4.86666667, 6.21666667, 5.53333333])
variances = np.array([0.07888889, 0.22805556, 0.06888889])

gaussian_function(np.array([5.2]), means, variances)

array([0.70236194, 0.08663994, 0.67857523])

In [23]:
means = np.array([3.36666667, 2.91666667, 1.81666667])
variances = np.array([0.09555556, 0.11138889, 0.08472222])

gaussian_function(np.array([2.4]), means, variances)

array([0.00971145, 0.36065659, 0.18397662])

In [27]:
0.00681*0.333+0.03122*0.333+0.1247*0.334

0.05431379

In [16]:
# compute manually

data_c0 = np.array([4.9, 4.7, 4.6, 5. , 5.4, 4.6])
mean_c0 = data_c0.mean()
var_c0  = data_c0.var()
print(mean_c0)
print(var_c0)      

prob_c0 = gaussian_function(data_c0, mean_c0, var_c0)
print(prob_c0)

1.52
0.1416
[1.00761742 0.40804972 0.893626   0.63670363 0.46995266]


In [17]:
data_c1 = np.array([3.8, 4.1, 3.9, 4.2, 3.4])
mean_c1 = data_c1.mean()
var_c1  = data_c1.var()
print(mean_c1)
print(var_c1)

prob_c1 = gaussian_function(data_c1, mean_c1, var_c1)
print(prob_c1)

3.88
0.07760000000000002
[1.37426395 1.0484362  1.42843305 0.74034542 0.3245289 ]


In [23]:
# predict manually

x_test = np.array([[3.0]])
dpf_c0_x = gaussian_function(x_test, mean_c0, var_c0)
dpf_c1_x = gaussian_function(x_test, mean_c1, var_c1)
print(dpf_c0_x)
print(dpf_c1_x)

# normalize
total = dpf_c0_x*0.5 + dpf_c1_x*0.5
print(total)
dpf_c0_x = dpf_c0_x*0.5/total
dpf_c1_x = dpf_c1_x*0.5/total

# print
print(dpf_c0_x)
print(dpf_c1_x)

[[0.00046381]]
[[0.00974954]]
[[0.00510668]]
[[0.0454125]]
[[0.9545875]]
