## Simple example

In [1]:
import numpy as np

heights = [48.6, 51.2, 59.1, 49.7, 58.2, 66.8, 63.1, 56.4, 54.5, 58.1]
heights = np.array(heights)
print(heights)

[48.6 51.2 59.1 49.7 58.2 66.8 63.1 56.4 54.5 58.1]


In [3]:
mean = np.mean(heights)
var  = np.var(heights)
dev  = np.sqrt(var)

print(mean)
print(var)
print(dev)

56.57000000000001
30.256099999999993
5.500554517500939


In [5]:
from scipy import stats

y_data = stats.norm.pdf(heights, mean, dev)
print(y_data)

[0.02538726 0.04503414 0.06524759 0.03324855 0.06941209 0.01286508
 0.0358485  0.07249302 0.06756954 0.06977551]


In [6]:
import math

def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var)) * np.exp(-(data-mean)**2 / (2*var))

output = gaussian_function(heights, mean, var)
print(output)

[0.02538726 0.04503414 0.06524759 0.03324855 0.06941209 0.01286508
 0.0358485  0.07249302 0.06756954 0.06977551]


In [10]:
gaussian_function(np.array([35.0]), mean, var)

array([3.32131093e-05])

In [1]:
import numpy as np

data = [1.4, 1.0, 1.3, 1.9, 2.0, 1.8]
data = np.array(data)
print(data)

[1.4 1.  1.3 1.9 2.  1.8]


In [2]:
mean = np.mean(data)
var  = np.var(data)
dev  = np.sqrt(var)

print(mean)
print(var)
print(dev)

1.5666666666666667
0.1288888888888889
0.3590109871423003


In [3]:
from scipy import stats

y_data = stats.norm.pdf(data, mean, dev)
print(y_data)

[0.99770776 0.31974678 0.84332884 0.7221151  0.53634132 0.8996557 ]


In [19]:
import numpy as np

data = [3.0, 3.8, 4.1, 3.9, 4.2, 3.4]
data = np.array(data)
print(data)

mean = np.mean(data)
var  = np.var(data)
dev  = np.sqrt(var)

print(mean)
print(var)
print(dev)

[3.  3.8 4.1 3.9 4.2 3.4]
3.733333333333333
0.1722222222222222
0.41499665326629104


In [21]:
from scipy import stats

y_data = stats.norm.pdf(data, mean, dev)
print(y_data)

[0.20174636 0.94899008 0.65065464 0.88683275 0.5108334  0.69625845]


In [22]:
import math

def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var)) * np.exp(-(data-mean)**2 / (2*var))

In [23]:
output = gaussian_function(data, mean, var)
print(output)

[0.20174636 0.94899008 0.65065464 0.88683275 0.5108334  0.69625845]


## Standard normal distribution

In [8]:
import numpy as np
from scipy import stats

data = [1.4, 1.0, 1.3, 1.9, 2.0, 1.8]
data = np.array(data)
print(data)

mean = np.mean(data)
var  = np.var(data)

print(mean)
print(var)

[1.4 1.  1.3 1.9 2.  1.8]
1.5666666666666667
0.1288888888888889


In [9]:
data = (data - mean) / var
print(data)

[-1.29310345 -4.39655172 -2.06896552  2.5862069   3.36206897  1.81034483]


In [10]:
y_data = stats.norm.pdf(data, 0, 1)
print(y_data)

[1.72907796e-01 2.53236437e-05 4.69229826e-02 1.40775832e-02
 1.40082715e-03 7.74895081e-02]
