## Example 1

In [17]:
import torch
import torch.nn as nn

Z = torch.Tensor([[1.2, 3.6, 0.1, -2.5]])
y = torch.Tensor([3]).long()
print(Z)
print(y)

tensor([[ 1.2000,  3.6000,  0.1000, -2.5000]])
tensor([3])


In [18]:
# Z: (N, C)
# y: (N,)
criterion = nn.CrossEntropyLoss()
loss = criterion(Z, y)
print(loss)

tensor(6.2161)


In [19]:
#=== verify 
softmax = nn.Softmax(dim=-1)
output = softmax(Z)
print(output)

tensor([[0.0808, 0.8903, 0.0269, 0.0020]])


In [20]:
import numpy as np

print(-np.log(0.0020))

6.214608098422191


## Example 2

In [23]:
import torch
import torch.nn as nn

N = 1
C = 3
d = 2

Z = torch.Tensor([1.2, 3.6, 0.1, -2.5, 0.1, -0.2]).reshape(N, C, d)
y = torch.Tensor([[1, 0]]).long()
print(Z[0, :, 0])
print(Z[0, :, 1])
print(y)

tensor([1.2000, 0.1000, 0.1000])
tensor([ 3.6000, -2.5000, -0.2000])
tensor([[1, 0]])


In [24]:
# Z: (N, C, d)
# y: (N, d)
criterion = nn.CrossEntropyLoss()
loss = criterion(Z, y)
print(loss)

tensor(0.8173)


In [25]:
#=== verify 
Z_p = Z.permute(0, 2, 1)
print(Z_p.shape)

softmax = nn.Softmax(dim=-1)
output = softmax(Z_p)
print(output)

torch.Size([1, 2, 3])
tensor([[[0.6003, 0.1998, 0.1998],
         [0.9760, 0.0022, 0.0218]]])


In [29]:
print(-np.log(0.1998))
print(-np.log(0.9760))
print( (1.6104+0.0242)/2 )

1.6104384127676838
0.024292692569044587
0.8173


## Example 3

In [1]:
import torch
import torch.nn as nn

N = 1
C = 3
d = 2

Z = torch.Tensor([1.2, 3.6, 0.1, -2.5, 0.1, -0.2]).reshape(N, C, d)
y = torch.Tensor([[1, 0]]).long()
print(Z[0, :, 0])
print(Z[0, :, 1])
print(y)

tensor([1.2000, 0.1000, 0.1000])
tensor([ 3.6000, -2.5000, -0.2000])
tensor([[1, 0]])


In [2]:
# Z: (N, C, d)
# y: (N, d)
criterion = nn.CrossEntropyLoss(ignore_index=1)
loss = criterion(Z, y)
print(loss)

tensor(0.0243)
